root: /
admin_dir: ZaCca_admin/
tpl: /user_data/packages/default/
admin_tpl: /user_data/packages/admin/
image_path: /upload/save_image/
root_dir: /var/www/html/eccube-3
root_urlpath: null
template_code: L3001templete
admin_route: ZaCca_admin
user_data_route: user_data
public_path: /html
public_path_realdir: /var/www/html/eccube-3/html
image_save_realdir: /var/www/html/eccube-3/html/upload/save_image
image_temp_realdir: /var/www/html/eccube-3/html/upload/temp_image
user_data_realdir: /var/www/html/eccube-3/html/user_data
block_default_realdir: /var/www/html/eccube-3/src/Eccube/Resource/template/default/Block
block_realdir: /var/www/html/eccube-3/app/template/L3001templete/Block
template_default_realdir: /var/www/html/eccube-3/src/Eccube/Resource/template/default
template_default_html_realdir: /var/www/html/eccube-3/html/template/default
template_admin_realdir: /var/www/html/eccube-3/src/Eccube/Resource/template/admin
template_admin_html_realdir: /var/www/html/eccube-3/html/template/admin
template_realdir: /var/www/html/eccube-3/app/template/L3001templete
template_html_realdir: /var/www/html/eccube-3/html/template/L3001templete
template_temp_realdir: /var/www/html/eccube-3/app/cache/eccube/template
csv_temp_realdir: /var/www/html/eccube-3/app/cache/eccube/csv
plugin_realdir: /var/www/html/eccube-3/app/Plugin
plugin_temp_realdir: /var/www/html/eccube-3/app/cache/plugin
plugin_html_realdir: /var/www/html/eccube-3/html/plugin
admin_urlpath: /template/admin
front_urlpath: /template/L3001templete
image_save_urlpath: /upload/save_image
image_temp_urlpath: /upload/temp_image
user_data_urlpath: /user_data
plugin_urlpath: /plugin
